import scala.util.Try

val a = Try(Nil.head)
//  la excepci√≥n queda almacenada en la variable a
// y no va a explotar
